### ISSUE TITLE
Use specific nsolid-registry tagged image

### ISSUE THREAD

**Issue by rosskukulinski** [nodesource/nsolid-kubernetes#11]
For example, see https://github.com/nodesource/nsolid-kubernetes/blob/master/conf/nsolid.quickstart.yml#L19

We should probably explicitly use a specific tagged image of the nsolid-registry.

**Comment by retrohacker** [comment]
:wave:

**Comment by retrohacker** [comment]
So the rationale behind this was that `etcd` is an internal implementation detail. We don't want to pass the burden of maintaining a version of `etcd` onto the user. If they need to pin to a specific version (which is understandable), they can pin to the hash of the image.
