### ISSUE TITLE
nginx-secure-proxy stuck with pending external ip

### ISSUE THREAD

**Issue by davglass** [nodesource/nsolid-kubernetes#18]
I tried the setup this morning, twice to be sure, but once I setup the AWS deploy of kuernetes I can access it's UI without issue. Once I run the `install` script here, everything appears to be fine until I run: `kubectl get svc nginx-secure-proxy --namespace=nsolid`

``` shell
NAME                 CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
nginx-secure-proxy   10.0.121.203   <pending>     80/TCP,443/TCP   21m
```

It just sits in this state, I can't get it to load the `nsolid` console so I can start trying it out :)

**Comment by davglass** [comment]
Doh, mis-clicked..

**Comment by nw** [comment]
Appears to be a permissions issues in your IAM policies. 

Is there anything interesting when you run
`kubectl describe svc nginx-secure-proxy --namespace=nsolid`

Particularly messages about access denied to perform elasticloadbalancing in the Events.

If this is the case please refer to this [fix](https://github.com/kubernetes/kubernetes/issues/10692#issuecomment-118447193)

**Comment by davglass** [comment]
Here's a snipit of the result:

```
  11s		6s		2	{service-controller }			Warning		CreatingLoadBalancerFailed	Error creating load balancer (will retry): Failed to create load balancer for service nsolid/nginx-secure-proxy: unsupported load balancer affinity: ClientIP
```

**Comment by nw** [comment]
@davglass what does `kubectl version` output?

**Comment by rosskukulinski** [comment]
@nw Looks like AWS ELB doesn't support Layer-4 proxy decisions based on client-ip. https://github.com/kubernetes/kubernetes/issues/13892

@davglass Removing [this line](https://github.com/nodesource/nsolid-kubernetes/blob/master/conf/nsolid.services.yml#L48) should make it work.  You'll need to `kubectl delete -f conf/nsolid.services.yml && kubectl create -f conf/nsolid.services.yml` to trigger an update.

**Comment by davglass** [comment]
@rosskukulinski I did those and I see this:

```shell
kubectl get svc nginx-secure-proxy --namespace=nsolid
NAME                 CLUSTER-IP    EXTERNAL-IP        PORT(S)          AGE
nginx-secure-proxy   10.0.84.180   af1485be258e5...   80/TCP,443/TCP   1m
```

**Comment by rosskukulinski** [comment]
@davglass perfect - the ELB has been created.  You can see the whole ELB url with:

```
kubectl --namespace=nsolid describe svc nginx-secure-proxy
```

**Comment by davglass** [comment]
Yup, I just didn't paste it in here :)

I can get to it, and I get the HTTP auth dialog. I enter the username/password for the demo and it just hangs.

**Comment by rosskukulinski** [comment]
👍   

What's the output of `kubectl --namespace=nsolid get pods`

**Comment by davglass** [comment]
```shell
$ kubectl --namespace=nsolid get pods
NAME                                 READY     STATUS    RESTARTS   AGE
console-3678399865-6xmr2             1/1       Running   0          42m
hub-1054140612-9abwa                 1/1       Running   0          42m
nginx-secure-proxy-241452110-fjph3   1/1       Running   0          42m
registry-1622600005-b6pj9            1/1       Running   0          42m
```
